### ISSUE TITLE
How to implement on specific screen?

### ISSUE THREAD

**Issue by lutfi-haslab** [batuhanoztrk/rn-screenshot-prevent#1]
I have implemented, but got blank screen on minimize app, like below image. I want to apply on specific screen. How to do it?

```
import RNScreenshotPrevent from 'rn-screenshot-prevent';

RNScreenshotPrevent.enabled(true);

if (Platform.OS === 'ios') RNScreenshotPrevent.enableSecureView();
```

![WhatsApp Image 2024-09-30 at 10 04 30](https://github.com/user-attachments/assets/a6298eb7-90f5-4409-9c22-649712ee9e7d)

**Comment by batuhanoztrk** [comment]
Hi @lutfi-haslab,

This behavior is actually expected because users should not be able to take screenshots even when they minimize the app. However, if you want to enable this feature on a specific screen, you can use the following code:

~~~typescript
import { useEffect } from 'react';
import RNScreenshotPrevent from 'rn-screenshot-prevent';

useEffect(() => {
  RNScreenshotPrevent.enabled(true);

  if (Platform.OS === 'ios') {
    RNScreenshotPrevent.enableSecureView();
  }

  return () => {
    RNScreenshotPrevent.enabled(false);

    if (Platform.OS === 'ios') {
      RNScreenshotPrevent.disableSecureView();
    }
  };
}, []);
~~~

This will enable `RNScreenshotPrevent` only for the specified screen, and it will be disabled when the component unmounts or the user navigates away from the screen.

If you encounter any issues with `disableSecureView`, please let me know, and I’ll be happy to assist you further!

Best regards! 🙌
